services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FRONTEND_ORIGIN=http://localhost:5173,http://frontend,http://frontend:80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:3000
    ports:
      - "5173:80"
    depends_on:
      - backend
